/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutLayoutRouteImport } from './routes/_layout/_layout'
import { Route as LayoutLangIndexRouteImport } from './routes/_layout/$lang/index'
import { Route as LayoutLangTermsServiceRouteImport } from './routes/_layout/$lang/terms-service'
import { Route as LayoutLangPrivacyPolicyRouteImport } from './routes/_layout/$lang/privacy-policy'
import { Route as LayoutLangContactRouteImport } from './routes/_layout/$lang/contact'
import { Route as LayoutLangAboutRouteImport } from './routes/_layout/$lang/about'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLayoutRoute = LayoutLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLangIndexRoute = LayoutLangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLangTermsServiceRoute = LayoutLangTermsServiceRouteImport.update({
  id: '/$lang/terms-service',
  path: '/$lang/terms-service',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLangPrivacyPolicyRoute = LayoutLangPrivacyPolicyRouteImport.update({
  id: '/$lang/privacy-policy',
  path: '/$lang/privacy-policy',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLangContactRoute = LayoutLangContactRouteImport.update({
  id: '/$lang/contact',
  path: '/$lang/contact',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLangAboutRoute = LayoutLangAboutRouteImport.update({
  id: '/$lang/about',
  path: '/$lang/about',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/$lang/about': typeof LayoutLangAboutRoute
  '/$lang/contact': typeof LayoutLangContactRoute
  '/$lang/privacy-policy': typeof LayoutLangPrivacyPolicyRoute
  '/$lang/terms-service': typeof LayoutLangTermsServiceRoute
  '/$lang': typeof LayoutLangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/$lang/about': typeof LayoutLangAboutRoute
  '/$lang/contact': typeof LayoutLangContactRoute
  '/$lang/privacy-policy': typeof LayoutLangPrivacyPolicyRoute
  '/$lang/terms-service': typeof LayoutLangTermsServiceRoute
  '/$lang': typeof LayoutLangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_layout': typeof LayoutLayoutRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/$lang/about': typeof LayoutLangAboutRoute
  '/_layout/$lang/contact': typeof LayoutLangContactRoute
  '/_layout/$lang/privacy-policy': typeof LayoutLangPrivacyPolicyRoute
  '/_layout/$lang/terms-service': typeof LayoutLangTermsServiceRoute
  '/_layout/$lang/': typeof LayoutLangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/privacy-policy'
    | '/$lang/terms-service'
    | '/$lang'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/privacy-policy'
    | '/$lang/terms-service'
    | '/$lang'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_layout'
    | '/_layout/'
    | '/_layout/$lang/about'
    | '/_layout/$lang/contact'
    | '/_layout/$lang/privacy-policy'
    | '/_layout/$lang/terms-service'
    | '/_layout/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_layout': {
      id: '/_layout/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutLayoutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$lang/': {
      id: '/_layout/$lang/'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LayoutLangIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$lang/terms-service': {
      id: '/_layout/$lang/terms-service'
      path: '/$lang/terms-service'
      fullPath: '/$lang/terms-service'
      preLoaderRoute: typeof LayoutLangTermsServiceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$lang/privacy-policy': {
      id: '/_layout/$lang/privacy-policy'
      path: '/$lang/privacy-policy'
      fullPath: '/$lang/privacy-policy'
      preLoaderRoute: typeof LayoutLangPrivacyPolicyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$lang/contact': {
      id: '/_layout/$lang/contact'
      path: '/$lang/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LayoutLangContactRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$lang/about': {
      id: '/_layout/$lang/about'
      path: '/$lang/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LayoutLangAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutLayoutRoute: typeof LayoutLayoutRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutLangAboutRoute: typeof LayoutLangAboutRoute
  LayoutLangContactRoute: typeof LayoutLangContactRoute
  LayoutLangPrivacyPolicyRoute: typeof LayoutLangPrivacyPolicyRoute
  LayoutLangTermsServiceRoute: typeof LayoutLangTermsServiceRoute
  LayoutLangIndexRoute: typeof LayoutLangIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutLayoutRoute: LayoutLayoutRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutLangAboutRoute: LayoutLangAboutRoute,
  LayoutLangContactRoute: LayoutLangContactRoute,
  LayoutLangPrivacyPolicyRoute: LayoutLangPrivacyPolicyRoute,
  LayoutLangTermsServiceRoute: LayoutLangTermsServiceRoute,
  LayoutLangIndexRoute: LayoutLangIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
